# Generated by Django 5.1.2 on 2024-11-18 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailing_finish_send_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="finish_send_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 18, 17, 57, 37, 120648),
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="first_send_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 18, 17, 57, 37, 120637),
                verbose_name="Дата и время первой отправки",
            ),
        ),
    ]
