# Generated by Django 5.1.2 on 2024-11-23 16:51

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_mailing_owner_message_owner_recipient_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="finish_send_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 24, 19, 51, 3, 61400),
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="first_send_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 23, 19, 51, 3, 61388),
                verbose_name="Дата и время первой отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Завершена"),
                    ("created", "Создана"),
                    ("running", "Запущена"),
                ],
                default="created",
                max_length=9,
                verbose_name="Статус автоматической рассылки",
            ),
        ),
    ]
